apiVersion: v1
kind: ConfigMap
metadata:
  name: os-service-config
  namespace: os-service
data:
  AWS_REGION: "us-east-1"
  SPRING_PROFILES_ACTIVE: "prod"
  LOG_LEVEL: "INFO"
  SERVER_PORT: "8081"
  DB_PORT: "5432"
  DB_NAME: "osservice_db"
  ENVIRONMENT: "production"
  NEW_RELIC_APP_NAME: "os-service"
  NEW_RELIC_ENABLED: "true"
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "os-service-group"
