apiVersion: v1
kind: Secret
metadata:
  name: os-service-secret
  namespace: os-service
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  NEW_RELIC_LICENSE_KEY: "CHANGE_ME"
  # Na produção, usar External Secrets Operator para sincronizar com AWS Secrets Manager
